### ISSUE TITLE
RKE2 is not configured correctly by ros-installer

### ISSUE THREAD

**Issue by kleberbaum** [rancher-sandbox/os2#126]
https://github.com/rancher-sandbox/os2/blob/304725eef5c0d6a47d53cd48ca899394668fa57a/docs/configuration.md?plain=#L47-L53
## Behavior in v0.1.0 with `ros-installer -config-file`:
```yaml
#cloud-config
hostname: "rke2"

# Assigns these keys to the first user in users or root if there
# is none
ssh_authorized_keys:
  - github:kleberbaum

# Rancherd configuration
rancherd:
  # The Kubernetes version to be installed. This must be a k3s or RKE2 version
  # v1.21 or newer. k3s and RKE2 versions always have a `k3s` or `rke2` in the
  # version string.
  # Valid versions are
  # k3s: curl -sL https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/release-v2.6/data/data.json | jq -r '.k3s.releases[].version'
  # RKE2: curl -sL https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/release-v2.6/data/data.json | jq -r '.rke2.releases[].version'
  kubernetesVersion: v1.23.6+rke2r2

  # The role of this node.  Every cluster must start with one node as role=cluster-init.
  # After that nodes can be joined using the server role for control-plane nodes and
  # agent role for worker only nodes.  The server/agent terms correspond to the server/agent
  # terms in k3s and RKE2
  role: server

# Any other cloud-init values can be included in this file and will be stored in
# /oem/99_custom.yaml of the installed image
```
```bash
localhost:~ # ros-installer -config-file https://gist.githubusercontent.com/kleberbaum/04ebf13ed040085cdea52fc99d38c970/raw/f2848c57ce8b8c4f7d5fcbbe4f19f5abb9d9eb04/rke2.yaml

Configuration
-------------

config_url: https://gist.githubusercontent.com/kleberbaum/04ebf13ed040085cdea52fc99d38c970/raw/f2848c57ce8b8c4f7d5fcbbe4f19f5abb9d9eb04/rke2.yaml
device: /dev/vda

Your disk will be formatted and installed with the above configuration.
Continue? [y/N]: y
```
### v0.1.0 with rke2, configured ssh-keys and hostname:
```bash
rke2:~ # cat /oem/99_custom.yaml
#cloud-config
hostname: rke2
rancherd:
  kubernetesVersion: v1.23.6+rke2r2
  role: server
rancheros: {}
ssh_authorized_keys:
- github:kleberbaum
```
```bash
rke2:~ # rke2 --version
rke2 version v1.23.6+rke2r2 (40d712e5081ac87e30e8f328f738130acf2c31f8)
go version go1.17.5b7
rke2:~ # kubectl version
W0515 10:52:40.472990    2725 loader.go:221] Config not found: /etc/rancher/k3s/k3s.yaml
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+rke2r2", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-28T19:13:01Z", GoVersion:"go1.17.9b7", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
```bash
rke2:~ # kubectl get pods --all-namespaces
W0515 10:54:05.649801    6529 loader.go:221] Config not found: /etc/rancher/k3s/k3s.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
![image](https://user-images.githubusercontent.com/26285351/168469387-590bdf3b-fbdc-4994-a376-794a06762dc7.png)
