### ISSUE TITLE
cloud-init: homedir and shell are required when creating new users

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/os2#13]
Booting with the following `cloud-init` file fails adding the vagrant user:

```yaml
#cloud-config

# Add additional users or set the password/ssh keys for root
users:
- name: "root"
  passwd: "ros"
  ssh_authorized_keys:
  - https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub
- name: "vagrant"
  passwd: "vagrant"
  ssh_authorized_keys:
  - https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub
```

`cos-setup-network`:
![Screenshot from 2022-02-11 10-04-16](https://user-images.githubusercontent.com/2420543/153564290-af28387a-c54b-41e9-b5ea-11697ecb56cf.png)
