### ISSUE TITLE
cloud-init: no ssh keys created for additional users

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/os2#15]
This seems to create the 'vagrant' user, but not the ssh keys (note, root had the keys correctly added):
```yaml
#cloud-config

# Add additional users or set the password/ssh keys for root
users:
- name: "root"
  passwd: "ros"
  ssh_authorized_keys:
  - https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub
- name: "vagrant"
  passwd: "vagrant"
  shell: "/bin/bash"
  homedir: "/run/vagrant"
  ssh_authorized_keys:
  - https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub
```

![Screenshot from 2022-02-11 10-04-16](https://user-images.githubusercontent.com/2420543/153564290-af28387a-c54b-41e9-b5ea-11697ecb56cf.png)

_Originally posted by @mudler in https://github.com/rancher-sandbox/os2/issues/13#issuecomment-1036014304_
