### ISSUE TITLE
extra yaml fields not functional when running manual installation

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/os2#24]
When an installation is performed manually with ros-installer `--config-file`, `runcmd`, and other extra YAML fields are not preserved:

Input config file:
```yaml
#cloud-config
rancherd:
  role: cluster-init
  rancherValues:
    features:
    - multi-cluster-management=true
ssh_authorized_keys:
  - github:mudler
runcmd:
  - curl -fL https://raw.githubusercontent.com/rancher/rancherd/master/install.sh | sh -
```

After install:

```bash
rancher-8421:/oem # cat 99_custom.yaml 
#cloud-config
rancheros: {}
ssh_authorized_keys:
- github:mudler
```

Seems ros-installer is manipulating the yaml fields in a way that extra fields are not carried over.
