### ISSUE TITLE
luet-mtree is enabled while installing from container images

### ISSUE THREAD

**Issue by ldevulder** [rancher-sandbox/os2#49]
Version used: https://github.com/rancher-sandbox/os2/releases/tag/v0.1.0-alpha20

I tried to provision of server with this config:
```
#cloud-config
rancheros:
    tpm:
        emulated: true
        seed: 5
    install:
        registrationCaCert: |-
            -----BEGIN CERTIFICATE-----
            [...]
            -----END CERTIFICATE-----
        registrationURL: https://epinio-k3s/v1-rancheros/registration/vzrn69vhqdjw6w54xrsqdwzkj5rkz2jhmqq8j8vd577x8k72mnthbr
        containerImage: quay.io/costoolkit/os2:v0.1.0-alpha20-amd64
```

Download of the container image was fine, but I ended up with a `luet` error:
```
Mar 10 15:41:22 localhost ros-installer[1756]:   ERROR     Plugin luet-mtree at /usr/bin/luet-mtree had an error: error while executing plugin: exit status 1
Mar 10 15:41:22 localhost ros-installer[1756]: panic: fatal error
```

I attached the whole log file.
[ros-installer.log](https://github.com/rancher-sandbox/os2/files/8224927/ros-installer.log)
