### ISSUE TITLE
CRD: `ManagedOSVersionChannel`

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/os2#63]
Part of https://github.com/rancher-sandbox/os2/issues/58

Create the following new CRDs and controller for the resources types described below
## `ManagedOSVersionChannel` and the controller

the `ManagedOSVersion` resources are populated by a controller, or either a kubernetes mechanism that satisfy `ManagedOSVersionChannel` source and constraints. The ManagedOSVersionChannel can be defined as such:

```
apiVersion: rancheros.cattle.io/v1
kind: ManagedOSVersionChannel
spec:
  type: "JSON"
  options: # map[string]interface{}
       url: "<file>.json"
```

where a type of channel (e.g. JSON, URL, XML, Github) populates `ManagedOSVersions` by using the specified options

It defines with which rules `ManagedOSVersion` should be populated (e.g. github repository tags, releases, a custom json file to parse)

The controller make sure to add labels/annotations where appropriately to notify that a ManagedOS version can be applied.

Ping the harvester team about their strategy and if it does cover their use cases too. Note they might have already a json file or something similar for their available versions, in which we might want to sync up within this card as we want to collect as much feedback as possible at this stage.

cc @bk201
