### ISSUE TITLE
Consume `ManagedOSVersion` from `ManagedOS`

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/os2#64]
Part of https://github.com/rancher-sandbox/os2/issues/58

Once https://github.com/rancher-sandbox/os2/issues/63 is in we can consume the new Kind with ManagedOS and trigger upgrades as usually

## `ManagedOS`

Managed OS needs to be able to refer to `ManagedOSVersions` for upgrades (extends it)

```
apiVersion: rancheros.cattle.io/v1
kind: ManagedOS
spec:
   # osImage: rancher/os2:v0.0.0
   managedVersionRef:
      name: "<X>"
```

We need the ManagedOS Kind to be able to refer to `ManagedOSVersions`
