### ISSUE TITLE
CRD: ManagedOSVersion

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/os2#78]
Part of https://github.com/rancher-sandbox/os2/issues/58

Create the following new CRDs and controller for the resources types described below

## `ManagedOSVersion`

`ManagedOSVersion` indicates the system version we want to upgrade to and that can be used within `ManagedOS`

```
apiVersion: rancheros.cattle.io/v1
kind: ManagedOSVersion
spec:
  version: <X>
  # or, if specified by any channel, a custom upgrade containerSpec
  upgradeContainerSpec: ...
  tags: [ "", "" ]
  minVersion: ""
  metadata: 
      <map[string]interface{}>
    CVEs: [" "] 
    Changelog: |....
```

The `ManagedOSVersion` declares its compatibility versions (range from which it can be upgraded to, and optional sets of constraints) and have to accomodate extra data (CVEs, Changelogs, etc ) this information have to be used purely from UI/UX interface, so we can treat them as metadata, but to keep in mind that has to be parsed programmatically somehow.
